name: mf2024-env
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - h5py
  - matplotlib
  - ipympl
  - colorspacious
  - ipywidgets
  - jupyterlab
  - jupyterlab-myst
  - 'nodejs>=20,<21'
  - mystmd
